#spring.application.name=bill-management
server:
  port: 8082
  servlet:
    context-path: "/bill-management"
spring:
  application:
    name: "bill-management"
#  name: bill_management_498h
  datasource:
    url: 'jdbc:mysql://localhost:3306/bill-management'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:postgresql://dpg-csuqsiij1k6c738iooig-a.singapore-postgres.render.com:5432/bill_management_498h
#    username: root
#    password: DlFzD87kCoICSJbWQNaQeFlJ2zfoPflh
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
#      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  # signature is generated in https://generate-random.org/encryption-key-generator?count=1&bytes=32&cipher=aes-256-cbc&string=&password=
  # with 32 bytes
  signer-key: "0eOPQ+UkuUGySUMc6raXHEUh0gTIAs8hzls6EJqbyD2Vlzjg/mOkF1P55Jl7I7HC"
  expiry:
    access-token: 3600 # in seconds
    refresh-token: 36000 # in seconds

